sonar.projectKey=FranciscoVacs_StringCalculator
sonar.organization=franciscovacs

#This is the name and version displayed in the SonarCloud UI.
sonar.projectName=StringCalculator
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=.
sonar.tests=.
sonar.exclusions=test_*.py,*_test.py,tests/**
sonar.test.inclusions=test_*.py,*_test.py,tests/**

sonar.language=py

sonar.python.coverage.reportPaths=coverage.xml


# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8